docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Introduction: intro.md
    - Reference:
      - Writers: writers.md
      - Filters: filters.md
      - Formatters: formatters.md
      - Processors: processors.md
    - 'PSR-3 Support': psr3.md
site_name: laminas-log
site_description: Laminas\Log
repo_url: 'https://github.com/laminas/laminas-log'
